// flow-typed signature: 08bee80c27ef9f375a66a178b7b4ab1c
// flow-typed version: <<STUB>>/styled-components_v^3.4.2/flow_v0.56.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'styled-components'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'styled-components' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'styled-components/dist/styled-components-no-parser.browser.cjs' {
  declare module.exports: any;
}

declare module 'styled-components/dist/styled-components-no-parser.browser.esm' {
  declare module.exports: any;
}

declare module 'styled-components/dist/styled-components-no-parser.cjs' {
  declare module.exports: any;
}

declare module 'styled-components/dist/styled-components-no-parser.esm' {
  declare module.exports: any;
}

declare module 'styled-components/dist/styled-components-primitivesm.cjs' {
  declare module.exports: any;
}

declare module 'styled-components/dist/styled-components-primitivesm.esm' {
  declare module.exports: any;
}

declare module 'styled-components/dist/styled-components.browser.cjs' {
  declare module.exports: any;
}

declare module 'styled-components/dist/styled-components.browser.cjs.min' {
  declare module.exports: any;
}

declare module 'styled-components/dist/styled-components.browser.esm' {
  declare module.exports: any;
}

declare module 'styled-components/dist/styled-components.browser.esm.min' {
  declare module.exports: any;
}

declare module 'styled-components/dist/styled-components.cjs' {
  declare module.exports: any;
}

declare module 'styled-components/dist/styled-components.cjs.min' {
  declare module.exports: any;
}

declare module 'styled-components/dist/styled-components.esm' {
  declare module.exports: any;
}

declare module 'styled-components/dist/styled-components.esm.min' {
  declare module.exports: any;
}

declare module 'styled-components/dist/styled-components' {
  declare module.exports: any;
}

declare module 'styled-components/dist/styled-components.min' {
  declare module.exports: any;
}

declare module 'styled-components/dist/styled-components.native.cjs' {
  declare module.exports: any;
}

declare module 'styled-components/flow-typed/danger-plugin-jest_vx.x.x' {
  declare module.exports: any;
}

declare module 'styled-components/flow-typed/enzyme_v3.x.x' {
  declare module.exports: any;
}

declare module 'styled-components/flow-typed/fbjs_vx.x.x' {
  declare module.exports: any;
}

declare module 'styled-components/flow-typed/npm/babel-cli_vx.x.x' {
  declare module.exports: any;
}

declare module 'styled-components/flow-typed/npm/babel-core_vx.x.x' {
  declare module.exports: any;
}

declare module 'styled-components/flow-typed/npm/babel-eslint_vx.x.x' {
  declare module.exports: any;
}

declare module 'styled-components/flow-typed/npm/babel-loader_vx.x.x' {
  declare module.exports: any;
}

declare module 'styled-components/flow-typed/npm/babel-plugin-add-module-exports_vx.x.x' {
  declare module.exports: any;
}

declare module 'styled-components/flow-typed/npm/babel-plugin-external-helpers_vx.x.x' {
  declare module.exports: any;
}

declare module 'styled-components/flow-typed/npm/babel-plugin-flow-react-proptypes_vx.x.x' {
  declare module.exports: any;
}

declare module 'styled-components/flow-typed/npm/babel-plugin-transform-class-properties_vx.x.x' {
  declare module.exports: any;
}

declare module 'styled-components/flow-typed/npm/babel-plugin-transform-flow-strip-types_vx.x.x' {
  declare module.exports: any;
}

declare module 'styled-components/flow-typed/npm/babel-plugin-transform-object-rest-spread_vx.x.x' {
  declare module.exports: any;
}

declare module 'styled-components/flow-typed/npm/babel-preset-latest_vx.x.x' {
  declare module.exports: any;
}

declare module 'styled-components/flow-typed/npm/babel-preset-react_vx.x.x' {
  declare module.exports: any;
}

declare module 'styled-components/flow-typed/npm/buffer_vx.x.x' {
  declare module.exports: any;
}

declare module 'styled-components/flow-typed/npm/chokidar_vx.x.x' {
  declare module.exports: any;
}

declare module 'styled-components/flow-typed/npm/css-to-react-native_v1.x.x' {
  declare module.exports: any;
}

declare module 'styled-components/flow-typed/npm/css-to-react-native_vx.x.x' {
  declare module.exports: any;
}

declare module 'styled-components/flow-typed/npm/eslint_vx.x.x' {
  declare module.exports: any;
}

declare module 'styled-components/flow-typed/npm/eslint-config-airbnb_vx.x.x' {
  declare module.exports: any;
}

declare module 'styled-components/flow-typed/npm/eslint-plugin-flowtype_vx.x.x' {
  declare module.exports: any;
}

declare module 'styled-components/flow-typed/npm/eslint-plugin-flowtype-errors_vx.x.x' {
  declare module.exports: any;
}

declare module 'styled-components/flow-typed/npm/eslint-plugin-import_vx.x.x' {
  declare module.exports: any;
}

declare module 'styled-components/flow-typed/npm/eslint-plugin-jsx-a11y_vx.x.x' {
  declare module.exports: any;
}

declare module 'styled-components/flow-typed/npm/eslint-plugin-react_vx.x.x' {
  declare module.exports: any;
}

declare module 'styled-components/flow-typed/npm/expect_vx.x.x' {
  declare module.exports: any;
}

declare module 'styled-components/flow-typed/npm/express_v4.x.x' {
  declare module.exports: any;
}

declare module 'styled-components/flow-typed/npm/flow-bin_v0.x.x' {
  declare module.exports: any;
}

declare module 'styled-components/flow-typed/npm/flow-copy-source_vx.x.x' {
  declare module.exports: any;
}

declare module 'styled-components/flow-typed/npm/inline-style-prefixer_vx.x.x' {
  declare module.exports: any;
}

declare module 'styled-components/flow-typed/npm/is-function_vx.x.x' {
  declare module.exports: any;
}

declare module 'styled-components/flow-typed/npm/is-plain-object_vx.x.x' {
  declare module.exports: any;
}

declare module 'styled-components/flow-typed/npm/jest_v19.x.x' {
  declare module.exports: any;
}

declare module 'styled-components/flow-typed/npm/jsdom_vx.x.x' {
  declare module.exports: any;
}

declare module 'styled-components/flow-typed/npm/lint-staged_vx.x.x' {
  declare module.exports: any;
}

declare module 'styled-components/flow-typed/npm/mocha_v2.4.x' {
  declare module.exports: any;
}

declare module 'styled-components/flow-typed/npm/mocha_v3.1.x' {
  declare module.exports: any;
}

declare module 'styled-components/flow-typed/npm/mocha-jsdom_vx.x.x' {
  declare module.exports: any;
}

declare module 'styled-components/flow-typed/npm/node-watch_vx.x.x' {
  declare module.exports: any;
}

declare module 'styled-components/flow-typed/npm/pre-commit_vx.x.x' {
  declare module.exports: any;
}

declare module 'styled-components/flow-typed/npm/react-addons-test-utils_v15.x.x' {
  declare module.exports: any;
}

declare module 'styled-components/flow-typed/npm/rollup_vx.x.x' {
  declare module.exports: any;
}

declare module 'styled-components/flow-typed/npm/rollup-plugin-babel_vx.x.x' {
  declare module.exports: any;
}

declare module 'styled-components/flow-typed/npm/rollup-plugin-commonjs_vx.x.x' {
  declare module.exports: any;
}

declare module 'styled-components/flow-typed/npm/rollup-plugin-flow_vx.x.x' {
  declare module.exports: any;
}

declare module 'styled-components/flow-typed/npm/rollup-plugin-inject_vx.x.x' {
  declare module.exports: any;
}

declare module 'styled-components/flow-typed/npm/rollup-plugin-json_vx.x.x' {
  declare module.exports: any;
}

declare module 'styled-components/flow-typed/npm/rollup-plugin-node-resolve_vx.x.x' {
  declare module.exports: any;
}

declare module 'styled-components/flow-typed/npm/rollup-plugin-replace_vx.x.x' {
  declare module.exports: any;
}

declare module 'styled-components/flow-typed/npm/rollup-plugin-uglify_vx.x.x' {
  declare module.exports: any;
}

declare module 'styled-components/flow-typed/npm/rollup-plugin-visualizer_vx.x.x' {
  declare module.exports: any;
}

declare module 'styled-components/flow-typed/npm/supports-color_v3.x.x' {
  declare module.exports: any;
}

declare module 'styled-components/flow-typed/react-native' {
  declare module.exports: any;
}

declare module 'styled-components/flow-typed/webpack-hotmodule' {
  declare module.exports: any;
}

declare module 'styled-components/lib/constructors/constructWithOptions' {
  declare module.exports: any;
}

declare module 'styled-components/lib/constructors/css' {
  declare module.exports: any;
}

declare module 'styled-components/lib/constructors/injectGlobal' {
  declare module.exports: any;
}

declare module 'styled-components/lib/constructors/keyframes' {
  declare module.exports: any;
}

declare module 'styled-components/lib/constructors/styled' {
  declare module.exports: any;
}

declare module 'styled-components/lib/hoc/withTheme' {
  declare module.exports: any;
}

declare module 'styled-components/lib/index' {
  declare module.exports: any;
}

declare module 'styled-components/lib/models/BrowserStyleSheet' {
  declare module.exports: any;
}

declare module 'styled-components/lib/models/ComponentStyle' {
  declare module.exports: any;
}

declare module 'styled-components/lib/models/InlineStyle' {
  declare module.exports: any;
}

declare module 'styled-components/lib/models/ServerStyleSheet' {
  declare module.exports: any;
}

declare module 'styled-components/lib/models/StyledComponent' {
  declare module.exports: any;
}

declare module 'styled-components/lib/models/StyledNativeComponent' {
  declare module.exports: any;
}

declare module 'styled-components/lib/models/StyleSheet' {
  declare module.exports: any;
}

declare module 'styled-components/lib/models/StyleSheetManager' {
  declare module.exports: any;
}

declare module 'styled-components/lib/models/ThemeProvider' {
  declare module.exports: any;
}

declare module 'styled-components/lib/native/index' {
  declare module.exports: any;
}

declare module 'styled-components/lib/no-parser/css' {
  declare module.exports: any;
}

declare module 'styled-components/lib/no-parser/flatten' {
  declare module.exports: any;
}

declare module 'styled-components/lib/no-parser/index' {
  declare module.exports: any;
}

declare module 'styled-components/lib/no-parser/stringifyRules' {
  declare module.exports: any;
}

declare module 'styled-components/lib/primitives/index' {
  declare module.exports: any;
}

declare module 'styled-components/lib/test/utils' {
  declare module.exports: any;
}

declare module 'styled-components/lib/types' {
  declare module.exports: any;
}

declare module 'styled-components/lib/utils/create-broadcast' {
  declare module.exports: any;
}

declare module 'styled-components/lib/utils/createWarnTooManyClasses' {
  declare module.exports: any;
}

declare module 'styled-components/lib/utils/determineTheme' {
  declare module.exports: any;
}

declare module 'styled-components/lib/utils/domElements' {
  declare module.exports: any;
}

declare module 'styled-components/lib/utils/escape' {
  declare module.exports: any;
}

declare module 'styled-components/lib/utils/extractCompsFromCSS' {
  declare module.exports: any;
}

declare module 'styled-components/lib/utils/flatten' {
  declare module.exports: any;
}

declare module 'styled-components/lib/utils/generateAlphabeticName' {
  declare module.exports: any;
}

declare module 'styled-components/lib/utils/getComponentName' {
  declare module.exports: any;
}

declare module 'styled-components/lib/utils/interleave' {
  declare module.exports: any;
}

declare module 'styled-components/lib/utils/isStyledComponent' {
  declare module.exports: any;
}

declare module 'styled-components/lib/utils/isTag' {
  declare module.exports: any;
}

declare module 'styled-components/lib/utils/nonce' {
  declare module.exports: any;
}

declare module 'styled-components/lib/utils/once' {
  declare module.exports: any;
}

declare module 'styled-components/lib/utils/stringifyRules' {
  declare module.exports: any;
}

declare module 'styled-components/lib/utils/validAttr' {
  declare module.exports: any;
}

declare module 'styled-components/lib/vendor/glamor/hash' {
  declare module.exports: any;
}

declare module 'styled-components/lib/vendor/postcss-nested/index' {
  declare module.exports: any;
}

declare module 'styled-components/lib/vendor/postcss-safe-parser/parse' {
  declare module.exports: any;
}

declare module 'styled-components/lib/vendor/postcss-safe-parser/safe-parser' {
  declare module.exports: any;
}

declare module 'styled-components/lib/vendor/postcss/at-rule' {
  declare module.exports: any;
}

declare module 'styled-components/lib/vendor/postcss/comment' {
  declare module.exports: any;
}

declare module 'styled-components/lib/vendor/postcss/container' {
  declare module.exports: any;
}

declare module 'styled-components/lib/vendor/postcss/css-syntax-error' {
  declare module.exports: any;
}

declare module 'styled-components/lib/vendor/postcss/declaration' {
  declare module.exports: any;
}

declare module 'styled-components/lib/vendor/postcss/input' {
  declare module.exports: any;
}

declare module 'styled-components/lib/vendor/postcss/lazy-result' {
  declare module.exports: any;
}

declare module 'styled-components/lib/vendor/postcss/list' {
  declare module.exports: any;
}

declare module 'styled-components/lib/vendor/postcss/node' {
  declare module.exports: any;
}

declare module 'styled-components/lib/vendor/postcss/parse' {
  declare module.exports: any;
}

declare module 'styled-components/lib/vendor/postcss/parser' {
  declare module.exports: any;
}

declare module 'styled-components/lib/vendor/postcss/postcss' {
  declare module.exports: any;
}

declare module 'styled-components/lib/vendor/postcss/processor' {
  declare module.exports: any;
}

declare module 'styled-components/lib/vendor/postcss/result' {
  declare module.exports: any;
}

declare module 'styled-components/lib/vendor/postcss/root' {
  declare module.exports: any;
}

declare module 'styled-components/lib/vendor/postcss/rule' {
  declare module.exports: any;
}

declare module 'styled-components/lib/vendor/postcss/stringifier' {
  declare module.exports: any;
}

declare module 'styled-components/lib/vendor/postcss/stringify' {
  declare module.exports: any;
}

declare module 'styled-components/lib/vendor/postcss/terminal-highlight' {
  declare module.exports: any;
}

declare module 'styled-components/lib/vendor/postcss/tokenize' {
  declare module.exports: any;
}

declare module 'styled-components/lib/vendor/postcss/vendor' {
  declare module.exports: any;
}

declare module 'styled-components/lib/vendor/postcss/warn-once' {
  declare module.exports: any;
}

declare module 'styled-components/lib/vendor/postcss/warning' {
  declare module.exports: any;
}

declare module 'styled-components/native/index' {
  declare module.exports: any;
}

declare module 'styled-components/scripts/postinstall' {
  declare module.exports: any;
}

declare module 'styled-components/src/constants' {
  declare module.exports: any;
}

declare module 'styled-components/src/constructors/constructWithOptions' {
  declare module.exports: any;
}

declare module 'styled-components/src/constructors/css' {
  declare module.exports: any;
}

declare module 'styled-components/src/constructors/injectGlobal' {
  declare module.exports: any;
}

declare module 'styled-components/src/constructors/keyframes' {
  declare module.exports: any;
}

declare module 'styled-components/src/constructors/styled' {
  declare module.exports: any;
}

declare module 'styled-components/src/constructors/test/injectGlobal.test' {
  declare module.exports: any;
}

declare module 'styled-components/src/constructors/test/keyframes.test' {
  declare module.exports: any;
}

declare module 'styled-components/src/constructors/test/styled.test' {
  declare module.exports: any;
}

declare module 'styled-components/src/hoc/withTheme' {
  declare module.exports: any;
}

declare module 'styled-components/src/index' {
  declare module.exports: any;
}

declare module 'styled-components/src/models/ComponentStyle' {
  declare module.exports: any;
}

declare module 'styled-components/src/models/InlineStyle' {
  declare module.exports: any;
}

declare module 'styled-components/src/models/ServerStyleSheet' {
  declare module.exports: any;
}

declare module 'styled-components/src/models/StyledComponent' {
  declare module.exports: any;
}

declare module 'styled-components/src/models/StyledNativeComponent' {
  declare module.exports: any;
}

declare module 'styled-components/src/models/StyleSheet' {
  declare module.exports: any;
}

declare module 'styled-components/src/models/StyleSheetManager' {
  declare module.exports: any;
}

declare module 'styled-components/src/models/StyleTags' {
  declare module.exports: any;
}

declare module 'styled-components/src/models/test/StyleSheetManager.test' {
  declare module.exports: any;
}

declare module 'styled-components/src/models/test/ThemeProvider.test' {
  declare module.exports: any;
}

declare module 'styled-components/src/models/ThemeProvider' {
  declare module.exports: any;
}

declare module 'styled-components/src/native/index' {
  declare module.exports: any;
}

declare module 'styled-components/src/native/test/native.test' {
  declare module.exports: any;
}

declare module 'styled-components/src/native/test/theme.test' {
  declare module.exports: any;
}

declare module 'styled-components/src/no-parser/css' {
  declare module.exports: any;
}

declare module 'styled-components/src/no-parser/flatten' {
  declare module.exports: any;
}

declare module 'styled-components/src/no-parser/index' {
  declare module.exports: any;
}

declare module 'styled-components/src/no-parser/stringifyRules' {
  declare module.exports: any;
}

declare module 'styled-components/src/no-parser/test/basic.test' {
  declare module.exports: any;
}

declare module 'styled-components/src/no-parser/test/flatten.test' {
  declare module.exports: any;
}

declare module 'styled-components/src/no-parser/test/keyframes.test' {
  declare module.exports: any;
}

declare module 'styled-components/src/primitives/index' {
  declare module.exports: any;
}

declare module 'styled-components/src/primitives/test/primitives.test' {
  declare module.exports: any;
}

declare module 'styled-components/src/secretInternals' {
  declare module.exports: any;
}

declare module 'styled-components/src/test/attrs.test' {
  declare module.exports: any;
}

declare module 'styled-components/src/test/basic.test' {
  declare module.exports: any;
}

declare module 'styled-components/src/test/constants.test' {
  declare module.exports: any;
}

declare module 'styled-components/src/test/css.test' {
  declare module.exports: any;
}

declare module 'styled-components/src/test/enzymeSetup' {
  declare module.exports: any;
}

declare module 'styled-components/src/test/expanded-api.test' {
  declare module.exports: any;
}

declare module 'styled-components/src/test/extending.test' {
  declare module.exports: any;
}

declare module 'styled-components/src/test/globals' {
  declare module.exports: any;
}

declare module 'styled-components/src/test/overriding.test' {
  declare module.exports: any;
}

declare module 'styled-components/src/test/props.test' {
  declare module.exports: any;
}

declare module 'styled-components/src/test/rehydration.test' {
  declare module.exports: any;
}

declare module 'styled-components/src/test/ssr.test' {
  declare module.exports: any;
}

declare module 'styled-components/src/test/staticCaching.test' {
  declare module.exports: any;
}

declare module 'styled-components/src/test/styles.test' {
  declare module.exports: any;
}

declare module 'styled-components/src/test/theme.test' {
  declare module.exports: any;
}

declare module 'styled-components/src/test/utils' {
  declare module.exports: any;
}

declare module 'styled-components/src/test/warnTooManyClasses.test' {
  declare module.exports: any;
}

declare module 'styled-components/src/types' {
  declare module.exports: any;
}

declare module 'styled-components/src/utils/consolidateStreamedStyles' {
  declare module.exports: any;
}

declare module 'styled-components/src/utils/create-broadcast' {
  declare module.exports: any;
}

declare module 'styled-components/src/utils/createWarnTooManyClasses' {
  declare module.exports: any;
}

declare module 'styled-components/src/utils/determineTheme' {
  declare module.exports: any;
}

declare module 'styled-components/src/utils/domElements' {
  declare module.exports: any;
}

declare module 'styled-components/src/utils/empties' {
  declare module.exports: any;
}

declare module 'styled-components/src/utils/error' {
  declare module.exports: any;
}

declare module 'styled-components/src/utils/escape' {
  declare module.exports: any;
}

declare module 'styled-components/src/utils/extractCompsFromCSS' {
  declare module.exports: any;
}

declare module 'styled-components/src/utils/flatten' {
  declare module.exports: any;
}

declare module 'styled-components/src/utils/generateAlphabeticName' {
  declare module.exports: any;
}

declare module 'styled-components/src/utils/generateDisplayName' {
  declare module.exports: any;
}

declare module 'styled-components/src/utils/getComponentName' {
  declare module.exports: any;
}

declare module 'styled-components/src/utils/hasInInheritanceChain' {
  declare module.exports: any;
}

declare module 'styled-components/src/utils/insertRuleHelpers' {
  declare module.exports: any;
}

declare module 'styled-components/src/utils/interleave' {
  declare module.exports: any;
}

declare module 'styled-components/src/utils/isPlainObject' {
  declare module.exports: any;
}

declare module 'styled-components/src/utils/isStyledComponent' {
  declare module.exports: any;
}

declare module 'styled-components/src/utils/isTag' {
  declare module.exports: any;
}

declare module 'styled-components/src/utils/nonce' {
  declare module.exports: any;
}

declare module 'styled-components/src/utils/once' {
  declare module.exports: any;
}

declare module 'styled-components/src/utils/stringifyRules' {
  declare module.exports: any;
}

declare module 'styled-components/src/utils/styleNames' {
  declare module.exports: any;
}

declare module 'styled-components/src/utils/test/determineTheme.test' {
  declare module.exports: any;
}

declare module 'styled-components/src/utils/test/error.test' {
  declare module.exports: any;
}

declare module 'styled-components/src/utils/test/escape.test' {
  declare module.exports: any;
}

declare module 'styled-components/src/utils/test/extractCompsFromCSS.test' {
  declare module.exports: any;
}

declare module 'styled-components/src/utils/test/flatten.test' {
  declare module.exports: any;
}

declare module 'styled-components/src/utils/test/generateAlphabeticName.test' {
  declare module.exports: any;
}

declare module 'styled-components/src/utils/test/generateDisplayName.test' {
  declare module.exports: any;
}

declare module 'styled-components/src/utils/test/getComponentName.test' {
  declare module.exports: any;
}

declare module 'styled-components/src/utils/test/interleave.test' {
  declare module.exports: any;
}

declare module 'styled-components/src/utils/test/styleNames.test' {
  declare module.exports: any;
}

declare module 'styled-components/src/utils/test/validAttr.test' {
  declare module.exports: any;
}

declare module 'styled-components/src/utils/validAttr' {
  declare module.exports: any;
}

declare module 'styled-components/src/vendor/glamor/hash' {
  declare module.exports: any;
}

declare module 'styled-components/src/vendor/postcss-nested/index' {
  declare module.exports: any;
}

declare module 'styled-components/src/vendor/postcss-safe-parser/parse' {
  declare module.exports: any;
}

declare module 'styled-components/src/vendor/postcss-safe-parser/safe-parser' {
  declare module.exports: any;
}

declare module 'styled-components/src/vendor/postcss/at-rule' {
  declare module.exports: any;
}

declare module 'styled-components/src/vendor/postcss/comment' {
  declare module.exports: any;
}

declare module 'styled-components/src/vendor/postcss/container' {
  declare module.exports: any;
}

declare module 'styled-components/src/vendor/postcss/css-syntax-error' {
  declare module.exports: any;
}

declare module 'styled-components/src/vendor/postcss/declaration' {
  declare module.exports: any;
}

declare module 'styled-components/src/vendor/postcss/input' {
  declare module.exports: any;
}

declare module 'styled-components/src/vendor/postcss/lazy-result' {
  declare module.exports: any;
}

declare module 'styled-components/src/vendor/postcss/list' {
  declare module.exports: any;
}

declare module 'styled-components/src/vendor/postcss/node' {
  declare module.exports: any;
}

declare module 'styled-components/src/vendor/postcss/parse' {
  declare module.exports: any;
}

declare module 'styled-components/src/vendor/postcss/parser' {
  declare module.exports: any;
}

declare module 'styled-components/src/vendor/postcss/postcss' {
  declare module.exports: any;
}

declare module 'styled-components/src/vendor/postcss/processor' {
  declare module.exports: any;
}

declare module 'styled-components/src/vendor/postcss/result' {
  declare module.exports: any;
}

declare module 'styled-components/src/vendor/postcss/root' {
  declare module.exports: any;
}

declare module 'styled-components/src/vendor/postcss/rule' {
  declare module.exports: any;
}

declare module 'styled-components/src/vendor/postcss/stringifier' {
  declare module.exports: any;
}

declare module 'styled-components/src/vendor/postcss/stringify' {
  declare module.exports: any;
}

declare module 'styled-components/src/vendor/postcss/terminal-highlight' {
  declare module.exports: any;
}

declare module 'styled-components/src/vendor/postcss/tokenize' {
  declare module.exports: any;
}

declare module 'styled-components/src/vendor/postcss/vendor' {
  declare module.exports: any;
}

declare module 'styled-components/src/vendor/postcss/warn-once' {
  declare module.exports: any;
}

declare module 'styled-components/src/vendor/postcss/warning' {
  declare module.exports: any;
}

declare module 'styled-components/test-utils/index' {
  declare module.exports: any;
}

declare module 'styled-components/test-utils/setupTestFramework' {
  declare module.exports: any;
}

// Filename aliases
declare module 'styled-components/dist/styled-components-no-parser.browser.cjs.js' {
  declare module.exports: $Exports<'styled-components/dist/styled-components-no-parser.browser.cjs'>;
}
declare module 'styled-components/dist/styled-components-no-parser.browser.esm.js' {
  declare module.exports: $Exports<'styled-components/dist/styled-components-no-parser.browser.esm'>;
}
declare module 'styled-components/dist/styled-components-no-parser.cjs.js' {
  declare module.exports: $Exports<'styled-components/dist/styled-components-no-parser.cjs'>;
}
declare module 'styled-components/dist/styled-components-no-parser.esm.js' {
  declare module.exports: $Exports<'styled-components/dist/styled-components-no-parser.esm'>;
}
declare module 'styled-components/dist/styled-components-primitivesm.cjs.js' {
  declare module.exports: $Exports<'styled-components/dist/styled-components-primitivesm.cjs'>;
}
declare module 'styled-components/dist/styled-components-primitivesm.esm.js' {
  declare module.exports: $Exports<'styled-components/dist/styled-components-primitivesm.esm'>;
}
declare module 'styled-components/dist/styled-components.browser.cjs.js' {
  declare module.exports: $Exports<'styled-components/dist/styled-components.browser.cjs'>;
}
declare module 'styled-components/dist/styled-components.browser.cjs.min.js' {
  declare module.exports: $Exports<'styled-components/dist/styled-components.browser.cjs.min'>;
}
declare module 'styled-components/dist/styled-components.browser.esm.js' {
  declare module.exports: $Exports<'styled-components/dist/styled-components.browser.esm'>;
}
declare module 'styled-components/dist/styled-components.browser.esm.min.js' {
  declare module.exports: $Exports<'styled-components/dist/styled-components.browser.esm.min'>;
}
declare module 'styled-components/dist/styled-components.cjs.js' {
  declare module.exports: $Exports<'styled-components/dist/styled-components.cjs'>;
}
declare module 'styled-components/dist/styled-components.cjs.min.js' {
  declare module.exports: $Exports<'styled-components/dist/styled-components.cjs.min'>;
}
declare module 'styled-components/dist/styled-components.esm.js' {
  declare module.exports: $Exports<'styled-components/dist/styled-components.esm'>;
}
declare module 'styled-components/dist/styled-components.esm.min.js' {
  declare module.exports: $Exports<'styled-components/dist/styled-components.esm.min'>;
}
declare module 'styled-components/dist/styled-components.js' {
  declare module.exports: $Exports<'styled-components/dist/styled-components'>;
}
declare module 'styled-components/dist/styled-components.min.js' {
  declare module.exports: $Exports<'styled-components/dist/styled-components.min'>;
}
declare module 'styled-components/dist/styled-components.native.cjs.js' {
  declare module.exports: $Exports<'styled-components/dist/styled-components.native.cjs'>;
}
declare module 'styled-components/flow-typed/danger-plugin-jest_vx.x.x.js' {
  declare module.exports: $Exports<'styled-components/flow-typed/danger-plugin-jest_vx.x.x'>;
}
declare module 'styled-components/flow-typed/enzyme_v3.x.x.js' {
  declare module.exports: $Exports<'styled-components/flow-typed/enzyme_v3.x.x'>;
}
declare module 'styled-components/flow-typed/fbjs_vx.x.x.js' {
  declare module.exports: $Exports<'styled-components/flow-typed/fbjs_vx.x.x'>;
}
declare module 'styled-components/flow-typed/npm/babel-cli_vx.x.x.js' {
  declare module.exports: $Exports<'styled-components/flow-typed/npm/babel-cli_vx.x.x'>;
}
declare module 'styled-components/flow-typed/npm/babel-core_vx.x.x.js' {
  declare module.exports: $Exports<'styled-components/flow-typed/npm/babel-core_vx.x.x'>;
}
declare module 'styled-components/flow-typed/npm/babel-eslint_vx.x.x.js' {
  declare module.exports: $Exports<'styled-components/flow-typed/npm/babel-eslint_vx.x.x'>;
}
declare module 'styled-components/flow-typed/npm/babel-loader_vx.x.x.js' {
  declare module.exports: $Exports<'styled-components/flow-typed/npm/babel-loader_vx.x.x'>;
}
declare module 'styled-components/flow-typed/npm/babel-plugin-add-module-exports_vx.x.x.js' {
  declare module.exports: $Exports<'styled-components/flow-typed/npm/babel-plugin-add-module-exports_vx.x.x'>;
}
declare module 'styled-components/flow-typed/npm/babel-plugin-external-helpers_vx.x.x.js' {
  declare module.exports: $Exports<'styled-components/flow-typed/npm/babel-plugin-external-helpers_vx.x.x'>;
}
declare module 'styled-components/flow-typed/npm/babel-plugin-flow-react-proptypes_vx.x.x.js' {
  declare module.exports: $Exports<'styled-components/flow-typed/npm/babel-plugin-flow-react-proptypes_vx.x.x'>;
}
declare module 'styled-components/flow-typed/npm/babel-plugin-transform-class-properties_vx.x.x.js' {
  declare module.exports: $Exports<'styled-components/flow-typed/npm/babel-plugin-transform-class-properties_vx.x.x'>;
}
declare module 'styled-components/flow-typed/npm/babel-plugin-transform-flow-strip-types_vx.x.x.js' {
  declare module.exports: $Exports<'styled-components/flow-typed/npm/babel-plugin-transform-flow-strip-types_vx.x.x'>;
}
declare module 'styled-components/flow-typed/npm/babel-plugin-transform-object-rest-spread_vx.x.x.js' {
  declare module.exports: $Exports<'styled-components/flow-typed/npm/babel-plugin-transform-object-rest-spread_vx.x.x'>;
}
declare module 'styled-components/flow-typed/npm/babel-preset-latest_vx.x.x.js' {
  declare module.exports: $Exports<'styled-components/flow-typed/npm/babel-preset-latest_vx.x.x'>;
}
declare module 'styled-components/flow-typed/npm/babel-preset-react_vx.x.x.js' {
  declare module.exports: $Exports<'styled-components/flow-typed/npm/babel-preset-react_vx.x.x'>;
}
declare module 'styled-components/flow-typed/npm/buffer_vx.x.x.js' {
  declare module.exports: $Exports<'styled-components/flow-typed/npm/buffer_vx.x.x'>;
}
declare module 'styled-components/flow-typed/npm/chokidar_vx.x.x.js' {
  declare module.exports: $Exports<'styled-components/flow-typed/npm/chokidar_vx.x.x'>;
}
declare module 'styled-components/flow-typed/npm/css-to-react-native_v1.x.x.js' {
  declare module.exports: $Exports<'styled-components/flow-typed/npm/css-to-react-native_v1.x.x'>;
}
declare module 'styled-components/flow-typed/npm/css-to-react-native_vx.x.x.js' {
  declare module.exports: $Exports<'styled-components/flow-typed/npm/css-to-react-native_vx.x.x'>;
}
declare module 'styled-components/flow-typed/npm/eslint_vx.x.x.js' {
  declare module.exports: $Exports<'styled-components/flow-typed/npm/eslint_vx.x.x'>;
}
declare module 'styled-components/flow-typed/npm/eslint-config-airbnb_vx.x.x.js' {
  declare module.exports: $Exports<'styled-components/flow-typed/npm/eslint-config-airbnb_vx.x.x'>;
}
declare module 'styled-components/flow-typed/npm/eslint-plugin-flowtype_vx.x.x.js' {
  declare module.exports: $Exports<'styled-components/flow-typed/npm/eslint-plugin-flowtype_vx.x.x'>;
}
declare module 'styled-components/flow-typed/npm/eslint-plugin-flowtype-errors_vx.x.x.js' {
  declare module.exports: $Exports<'styled-components/flow-typed/npm/eslint-plugin-flowtype-errors_vx.x.x'>;
}
declare module 'styled-components/flow-typed/npm/eslint-plugin-import_vx.x.x.js' {
  declare module.exports: $Exports<'styled-components/flow-typed/npm/eslint-plugin-import_vx.x.x'>;
}
declare module 'styled-components/flow-typed/npm/eslint-plugin-jsx-a11y_vx.x.x.js' {
  declare module.exports: $Exports<'styled-components/flow-typed/npm/eslint-plugin-jsx-a11y_vx.x.x'>;
}
declare module 'styled-components/flow-typed/npm/eslint-plugin-react_vx.x.x.js' {
  declare module.exports: $Exports<'styled-components/flow-typed/npm/eslint-plugin-react_vx.x.x'>;
}
declare module 'styled-components/flow-typed/npm/expect_vx.x.x.js' {
  declare module.exports: $Exports<'styled-components/flow-typed/npm/expect_vx.x.x'>;
}
declare module 'styled-components/flow-typed/npm/express_v4.x.x.js' {
  declare module.exports: $Exports<'styled-components/flow-typed/npm/express_v4.x.x'>;
}
declare module 'styled-components/flow-typed/npm/flow-bin_v0.x.x.js' {
  declare module.exports: $Exports<'styled-components/flow-typed/npm/flow-bin_v0.x.x'>;
}
declare module 'styled-components/flow-typed/npm/flow-copy-source_vx.x.x.js' {
  declare module.exports: $Exports<'styled-components/flow-typed/npm/flow-copy-source_vx.x.x'>;
}
declare module 'styled-components/flow-typed/npm/inline-style-prefixer_vx.x.x.js' {
  declare module.exports: $Exports<'styled-components/flow-typed/npm/inline-style-prefixer_vx.x.x'>;
}
declare module 'styled-components/flow-typed/npm/is-function_vx.x.x.js' {
  declare module.exports: $Exports<'styled-components/flow-typed/npm/is-function_vx.x.x'>;
}
declare module 'styled-components/flow-typed/npm/is-plain-object_vx.x.x.js' {
  declare module.exports: $Exports<'styled-components/flow-typed/npm/is-plain-object_vx.x.x'>;
}
declare module 'styled-components/flow-typed/npm/jest_v19.x.x.js' {
  declare module.exports: $Exports<'styled-components/flow-typed/npm/jest_v19.x.x'>;
}
declare module 'styled-components/flow-typed/npm/jsdom_vx.x.x.js' {
  declare module.exports: $Exports<'styled-components/flow-typed/npm/jsdom_vx.x.x'>;
}
declare module 'styled-components/flow-typed/npm/lint-staged_vx.x.x.js' {
  declare module.exports: $Exports<'styled-components/flow-typed/npm/lint-staged_vx.x.x'>;
}
declare module 'styled-components/flow-typed/npm/mocha_v2.4.x.js' {
  declare module.exports: $Exports<'styled-components/flow-typed/npm/mocha_v2.4.x'>;
}
declare module 'styled-components/flow-typed/npm/mocha_v3.1.x.js' {
  declare module.exports: $Exports<'styled-components/flow-typed/npm/mocha_v3.1.x'>;
}
declare module 'styled-components/flow-typed/npm/mocha-jsdom_vx.x.x.js' {
  declare module.exports: $Exports<'styled-components/flow-typed/npm/mocha-jsdom_vx.x.x'>;
}
declare module 'styled-components/flow-typed/npm/node-watch_vx.x.x.js' {
  declare module.exports: $Exports<'styled-components/flow-typed/npm/node-watch_vx.x.x'>;
}
declare module 'styled-components/flow-typed/npm/pre-commit_vx.x.x.js' {
  declare module.exports: $Exports<'styled-components/flow-typed/npm/pre-commit_vx.x.x'>;
}
declare module 'styled-components/flow-typed/npm/react-addons-test-utils_v15.x.x.js' {
  declare module.exports: $Exports<'styled-components/flow-typed/npm/react-addons-test-utils_v15.x.x'>;
}
declare module 'styled-components/flow-typed/npm/rollup_vx.x.x.js' {
  declare module.exports: $Exports<'styled-components/flow-typed/npm/rollup_vx.x.x'>;
}
declare module 'styled-components/flow-typed/npm/rollup-plugin-babel_vx.x.x.js' {
  declare module.exports: $Exports<'styled-components/flow-typed/npm/rollup-plugin-babel_vx.x.x'>;
}
declare module 'styled-components/flow-typed/npm/rollup-plugin-commonjs_vx.x.x.js' {
  declare module.exports: $Exports<'styled-components/flow-typed/npm/rollup-plugin-commonjs_vx.x.x'>;
}
declare module 'styled-components/flow-typed/npm/rollup-plugin-flow_vx.x.x.js' {
  declare module.exports: $Exports<'styled-components/flow-typed/npm/rollup-plugin-flow_vx.x.x'>;
}
declare module 'styled-components/flow-typed/npm/rollup-plugin-inject_vx.x.x.js' {
  declare module.exports: $Exports<'styled-components/flow-typed/npm/rollup-plugin-inject_vx.x.x'>;
}
declare module 'styled-components/flow-typed/npm/rollup-plugin-json_vx.x.x.js' {
  declare module.exports: $Exports<'styled-components/flow-typed/npm/rollup-plugin-json_vx.x.x'>;
}
declare module 'styled-components/flow-typed/npm/rollup-plugin-node-resolve_vx.x.x.js' {
  declare module.exports: $Exports<'styled-components/flow-typed/npm/rollup-plugin-node-resolve_vx.x.x'>;
}
declare module 'styled-components/flow-typed/npm/rollup-plugin-replace_vx.x.x.js' {
  declare module.exports: $Exports<'styled-components/flow-typed/npm/rollup-plugin-replace_vx.x.x'>;
}
declare module 'styled-components/flow-typed/npm/rollup-plugin-uglify_vx.x.x.js' {
  declare module.exports: $Exports<'styled-components/flow-typed/npm/rollup-plugin-uglify_vx.x.x'>;
}
declare module 'styled-components/flow-typed/npm/rollup-plugin-visualizer_vx.x.x.js' {
  declare module.exports: $Exports<'styled-components/flow-typed/npm/rollup-plugin-visualizer_vx.x.x'>;
}
declare module 'styled-components/flow-typed/npm/supports-color_v3.x.x.js' {
  declare module.exports: $Exports<'styled-components/flow-typed/npm/supports-color_v3.x.x'>;
}
declare module 'styled-components/flow-typed/react-native.js' {
  declare module.exports: $Exports<'styled-components/flow-typed/react-native'>;
}
declare module 'styled-components/flow-typed/webpack-hotmodule.js' {
  declare module.exports: $Exports<'styled-components/flow-typed/webpack-hotmodule'>;
}
declare module 'styled-components/lib/constructors/constructWithOptions.js' {
  declare module.exports: $Exports<'styled-components/lib/constructors/constructWithOptions'>;
}
declare module 'styled-components/lib/constructors/css.js' {
  declare module.exports: $Exports<'styled-components/lib/constructors/css'>;
}
declare module 'styled-components/lib/constructors/injectGlobal.js' {
  declare module.exports: $Exports<'styled-components/lib/constructors/injectGlobal'>;
}
declare module 'styled-components/lib/constructors/keyframes.js' {
  declare module.exports: $Exports<'styled-components/lib/constructors/keyframes'>;
}
declare module 'styled-components/lib/constructors/styled.js' {
  declare module.exports: $Exports<'styled-components/lib/constructors/styled'>;
}
declare module 'styled-components/lib/hoc/withTheme.js' {
  declare module.exports: $Exports<'styled-components/lib/hoc/withTheme'>;
}
declare module 'styled-components/lib/index.js' {
  declare module.exports: $Exports<'styled-components/lib/index'>;
}
declare module 'styled-components/lib/models/BrowserStyleSheet.js' {
  declare module.exports: $Exports<'styled-components/lib/models/BrowserStyleSheet'>;
}
declare module 'styled-components/lib/models/ComponentStyle.js' {
  declare module.exports: $Exports<'styled-components/lib/models/ComponentStyle'>;
}
declare module 'styled-components/lib/models/InlineStyle.js' {
  declare module.exports: $Exports<'styled-components/lib/models/InlineStyle'>;
}
declare module 'styled-components/lib/models/ServerStyleSheet.js' {
  declare module.exports: $Exports<'styled-components/lib/models/ServerStyleSheet'>;
}
declare module 'styled-components/lib/models/StyledComponent.js' {
  declare module.exports: $Exports<'styled-components/lib/models/StyledComponent'>;
}
declare module 'styled-components/lib/models/StyledNativeComponent.js' {
  declare module.exports: $Exports<'styled-components/lib/models/StyledNativeComponent'>;
}
declare module 'styled-components/lib/models/StyleSheet.js' {
  declare module.exports: $Exports<'styled-components/lib/models/StyleSheet'>;
}
declare module 'styled-components/lib/models/StyleSheetManager.js' {
  declare module.exports: $Exports<'styled-components/lib/models/StyleSheetManager'>;
}
declare module 'styled-components/lib/models/ThemeProvider.js' {
  declare module.exports: $Exports<'styled-components/lib/models/ThemeProvider'>;
}
declare module 'styled-components/lib/native/index.js' {
  declare module.exports: $Exports<'styled-components/lib/native/index'>;
}
declare module 'styled-components/lib/no-parser/css.js' {
  declare module.exports: $Exports<'styled-components/lib/no-parser/css'>;
}
declare module 'styled-components/lib/no-parser/flatten.js' {
  declare module.exports: $Exports<'styled-components/lib/no-parser/flatten'>;
}
declare module 'styled-components/lib/no-parser/index.js' {
  declare module.exports: $Exports<'styled-components/lib/no-parser/index'>;
}
declare module 'styled-components/lib/no-parser/stringifyRules.js' {
  declare module.exports: $Exports<'styled-components/lib/no-parser/stringifyRules'>;
}
declare module 'styled-components/lib/primitives/index.js' {
  declare module.exports: $Exports<'styled-components/lib/primitives/index'>;
}
declare module 'styled-components/lib/test/utils.js' {
  declare module.exports: $Exports<'styled-components/lib/test/utils'>;
}
declare module 'styled-components/lib/types.js' {
  declare module.exports: $Exports<'styled-components/lib/types'>;
}
declare module 'styled-components/lib/utils/create-broadcast.js' {
  declare module.exports: $Exports<'styled-components/lib/utils/create-broadcast'>;
}
declare module 'styled-components/lib/utils/createWarnTooManyClasses.js' {
  declare module.exports: $Exports<'styled-components/lib/utils/createWarnTooManyClasses'>;
}
declare module 'styled-components/lib/utils/determineTheme.js' {
  declare module.exports: $Exports<'styled-components/lib/utils/determineTheme'>;
}
declare module 'styled-components/lib/utils/domElements.js' {
  declare module.exports: $Exports<'styled-components/lib/utils/domElements'>;
}
declare module 'styled-components/lib/utils/escape.js' {
  declare module.exports: $Exports<'styled-components/lib/utils/escape'>;
}
declare module 'styled-components/lib/utils/extractCompsFromCSS.js' {
  declare module.exports: $Exports<'styled-components/lib/utils/extractCompsFromCSS'>;
}
declare module 'styled-components/lib/utils/flatten.js' {
  declare module.exports: $Exports<'styled-components/lib/utils/flatten'>;
}
declare module 'styled-components/lib/utils/generateAlphabeticName.js' {
  declare module.exports: $Exports<'styled-components/lib/utils/generateAlphabeticName'>;
}
declare module 'styled-components/lib/utils/getComponentName.js' {
  declare module.exports: $Exports<'styled-components/lib/utils/getComponentName'>;
}
declare module 'styled-components/lib/utils/interleave.js' {
  declare module.exports: $Exports<'styled-components/lib/utils/interleave'>;
}
declare module 'styled-components/lib/utils/isStyledComponent.js' {
  declare module.exports: $Exports<'styled-components/lib/utils/isStyledComponent'>;
}
declare module 'styled-components/lib/utils/isTag.js' {
  declare module.exports: $Exports<'styled-components/lib/utils/isTag'>;
}
declare module 'styled-components/lib/utils/nonce.js' {
  declare module.exports: $Exports<'styled-components/lib/utils/nonce'>;
}
declare module 'styled-components/lib/utils/once.js' {
  declare module.exports: $Exports<'styled-components/lib/utils/once'>;
}
declare module 'styled-components/lib/utils/stringifyRules.js' {
  declare module.exports: $Exports<'styled-components/lib/utils/stringifyRules'>;
}
declare module 'styled-components/lib/utils/validAttr.js' {
  declare module.exports: $Exports<'styled-components/lib/utils/validAttr'>;
}
declare module 'styled-components/lib/vendor/glamor/hash.js' {
  declare module.exports: $Exports<'styled-components/lib/vendor/glamor/hash'>;
}
declare module 'styled-components/lib/vendor/postcss-nested/index.js' {
  declare module.exports: $Exports<'styled-components/lib/vendor/postcss-nested/index'>;
}
declare module 'styled-components/lib/vendor/postcss-safe-parser/parse.js' {
  declare module.exports: $Exports<'styled-components/lib/vendor/postcss-safe-parser/parse'>;
}
declare module 'styled-components/lib/vendor/postcss-safe-parser/safe-parser.js' {
  declare module.exports: $Exports<'styled-components/lib/vendor/postcss-safe-parser/safe-parser'>;
}
declare module 'styled-components/lib/vendor/postcss/at-rule.js' {
  declare module.exports: $Exports<'styled-components/lib/vendor/postcss/at-rule'>;
}
declare module 'styled-components/lib/vendor/postcss/comment.js' {
  declare module.exports: $Exports<'styled-components/lib/vendor/postcss/comment'>;
}
declare module 'styled-components/lib/vendor/postcss/container.js' {
  declare module.exports: $Exports<'styled-components/lib/vendor/postcss/container'>;
}
declare module 'styled-components/lib/vendor/postcss/css-syntax-error.js' {
  declare module.exports: $Exports<'styled-components/lib/vendor/postcss/css-syntax-error'>;
}
declare module 'styled-components/lib/vendor/postcss/declaration.js' {
  declare module.exports: $Exports<'styled-components/lib/vendor/postcss/declaration'>;
}
declare module 'styled-components/lib/vendor/postcss/input.js' {
  declare module.exports: $Exports<'styled-components/lib/vendor/postcss/input'>;
}
declare module 'styled-components/lib/vendor/postcss/lazy-result.js' {
  declare module.exports: $Exports<'styled-components/lib/vendor/postcss/lazy-result'>;
}
declare module 'styled-components/lib/vendor/postcss/list.js' {
  declare module.exports: $Exports<'styled-components/lib/vendor/postcss/list'>;
}
declare module 'styled-components/lib/vendor/postcss/node.js' {
  declare module.exports: $Exports<'styled-components/lib/vendor/postcss/node'>;
}
declare module 'styled-components/lib/vendor/postcss/parse.js' {
  declare module.exports: $Exports<'styled-components/lib/vendor/postcss/parse'>;
}
declare module 'styled-components/lib/vendor/postcss/parser.js' {
  declare module.exports: $Exports<'styled-components/lib/vendor/postcss/parser'>;
}
declare module 'styled-components/lib/vendor/postcss/postcss.js' {
  declare module.exports: $Exports<'styled-components/lib/vendor/postcss/postcss'>;
}
declare module 'styled-components/lib/vendor/postcss/processor.js' {
  declare module.exports: $Exports<'styled-components/lib/vendor/postcss/processor'>;
}
declare module 'styled-components/lib/vendor/postcss/result.js' {
  declare module.exports: $Exports<'styled-components/lib/vendor/postcss/result'>;
}
declare module 'styled-components/lib/vendor/postcss/root.js' {
  declare module.exports: $Exports<'styled-components/lib/vendor/postcss/root'>;
}
declare module 'styled-components/lib/vendor/postcss/rule.js' {
  declare module.exports: $Exports<'styled-components/lib/vendor/postcss/rule'>;
}
declare module 'styled-components/lib/vendor/postcss/stringifier.js' {
  declare module.exports: $Exports<'styled-components/lib/vendor/postcss/stringifier'>;
}
declare module 'styled-components/lib/vendor/postcss/stringify.js' {
  declare module.exports: $Exports<'styled-components/lib/vendor/postcss/stringify'>;
}
declare module 'styled-components/lib/vendor/postcss/terminal-highlight.js' {
  declare module.exports: $Exports<'styled-components/lib/vendor/postcss/terminal-highlight'>;
}
declare module 'styled-components/lib/vendor/postcss/tokenize.js' {
  declare module.exports: $Exports<'styled-components/lib/vendor/postcss/tokenize'>;
}
declare module 'styled-components/lib/vendor/postcss/vendor.js' {
  declare module.exports: $Exports<'styled-components/lib/vendor/postcss/vendor'>;
}
declare module 'styled-components/lib/vendor/postcss/warn-once.js' {
  declare module.exports: $Exports<'styled-components/lib/vendor/postcss/warn-once'>;
}
declare module 'styled-components/lib/vendor/postcss/warning.js' {
  declare module.exports: $Exports<'styled-components/lib/vendor/postcss/warning'>;
}
declare module 'styled-components/native/index.js' {
  declare module.exports: $Exports<'styled-components/native/index'>;
}
declare module 'styled-components/scripts/postinstall.js' {
  declare module.exports: $Exports<'styled-components/scripts/postinstall'>;
}
declare module 'styled-components/src/constants.js' {
  declare module.exports: $Exports<'styled-components/src/constants'>;
}
declare module 'styled-components/src/constructors/constructWithOptions.js' {
  declare module.exports: $Exports<'styled-components/src/constructors/constructWithOptions'>;
}
declare module 'styled-components/src/constructors/css.js' {
  declare module.exports: $Exports<'styled-components/src/constructors/css'>;
}
declare module 'styled-components/src/constructors/injectGlobal.js' {
  declare module.exports: $Exports<'styled-components/src/constructors/injectGlobal'>;
}
declare module 'styled-components/src/constructors/keyframes.js' {
  declare module.exports: $Exports<'styled-components/src/constructors/keyframes'>;
}
declare module 'styled-components/src/constructors/styled.js' {
  declare module.exports: $Exports<'styled-components/src/constructors/styled'>;
}
declare module 'styled-components/src/constructors/test/injectGlobal.test.js' {
  declare module.exports: $Exports<'styled-components/src/constructors/test/injectGlobal.test'>;
}
declare module 'styled-components/src/constructors/test/keyframes.test.js' {
  declare module.exports: $Exports<'styled-components/src/constructors/test/keyframes.test'>;
}
declare module 'styled-components/src/constructors/test/styled.test.js' {
  declare module.exports: $Exports<'styled-components/src/constructors/test/styled.test'>;
}
declare module 'styled-components/src/hoc/withTheme.js' {
  declare module.exports: $Exports<'styled-components/src/hoc/withTheme'>;
}
declare module 'styled-components/src/index.js' {
  declare module.exports: $Exports<'styled-components/src/index'>;
}
declare module 'styled-components/src/models/ComponentStyle.js' {
  declare module.exports: $Exports<'styled-components/src/models/ComponentStyle'>;
}
declare module 'styled-components/src/models/InlineStyle.js' {
  declare module.exports: $Exports<'styled-components/src/models/InlineStyle'>;
}
declare module 'styled-components/src/models/ServerStyleSheet.js' {
  declare module.exports: $Exports<'styled-components/src/models/ServerStyleSheet'>;
}
declare module 'styled-components/src/models/StyledComponent.js' {
  declare module.exports: $Exports<'styled-components/src/models/StyledComponent'>;
}
declare module 'styled-components/src/models/StyledNativeComponent.js' {
  declare module.exports: $Exports<'styled-components/src/models/StyledNativeComponent'>;
}
declare module 'styled-components/src/models/StyleSheet.js' {
  declare module.exports: $Exports<'styled-components/src/models/StyleSheet'>;
}
declare module 'styled-components/src/models/StyleSheetManager.js' {
  declare module.exports: $Exports<'styled-components/src/models/StyleSheetManager'>;
}
declare module 'styled-components/src/models/StyleTags.js' {
  declare module.exports: $Exports<'styled-components/src/models/StyleTags'>;
}
declare module 'styled-components/src/models/test/StyleSheetManager.test.js' {
  declare module.exports: $Exports<'styled-components/src/models/test/StyleSheetManager.test'>;
}
declare module 'styled-components/src/models/test/ThemeProvider.test.js' {
  declare module.exports: $Exports<'styled-components/src/models/test/ThemeProvider.test'>;
}
declare module 'styled-components/src/models/ThemeProvider.js' {
  declare module.exports: $Exports<'styled-components/src/models/ThemeProvider'>;
}
declare module 'styled-components/src/native/index.js' {
  declare module.exports: $Exports<'styled-components/src/native/index'>;
}
declare module 'styled-components/src/native/test/native.test.js' {
  declare module.exports: $Exports<'styled-components/src/native/test/native.test'>;
}
declare module 'styled-components/src/native/test/theme.test.js' {
  declare module.exports: $Exports<'styled-components/src/native/test/theme.test'>;
}
declare module 'styled-components/src/no-parser/css.js' {
  declare module.exports: $Exports<'styled-components/src/no-parser/css'>;
}
declare module 'styled-components/src/no-parser/flatten.js' {
  declare module.exports: $Exports<'styled-components/src/no-parser/flatten'>;
}
declare module 'styled-components/src/no-parser/index.js' {
  declare module.exports: $Exports<'styled-components/src/no-parser/index'>;
}
declare module 'styled-components/src/no-parser/stringifyRules.js' {
  declare module.exports: $Exports<'styled-components/src/no-parser/stringifyRules'>;
}
declare module 'styled-components/src/no-parser/test/basic.test.js' {
  declare module.exports: $Exports<'styled-components/src/no-parser/test/basic.test'>;
}
declare module 'styled-components/src/no-parser/test/flatten.test.js' {
  declare module.exports: $Exports<'styled-components/src/no-parser/test/flatten.test'>;
}
declare module 'styled-components/src/no-parser/test/keyframes.test.js' {
  declare module.exports: $Exports<'styled-components/src/no-parser/test/keyframes.test'>;
}
declare module 'styled-components/src/primitives/index.js' {
  declare module.exports: $Exports<'styled-components/src/primitives/index'>;
}
declare module 'styled-components/src/primitives/test/primitives.test.js' {
  declare module.exports: $Exports<'styled-components/src/primitives/test/primitives.test'>;
}
declare module 'styled-components/src/secretInternals.js' {
  declare module.exports: $Exports<'styled-components/src/secretInternals'>;
}
declare module 'styled-components/src/test/attrs.test.js' {
  declare module.exports: $Exports<'styled-components/src/test/attrs.test'>;
}
declare module 'styled-components/src/test/basic.test.js' {
  declare module.exports: $Exports<'styled-components/src/test/basic.test'>;
}
declare module 'styled-components/src/test/constants.test.js' {
  declare module.exports: $Exports<'styled-components/src/test/constants.test'>;
}
declare module 'styled-components/src/test/css.test.js' {
  declare module.exports: $Exports<'styled-components/src/test/css.test'>;
}
declare module 'styled-components/src/test/enzymeSetup.js' {
  declare module.exports: $Exports<'styled-components/src/test/enzymeSetup'>;
}
declare module 'styled-components/src/test/expanded-api.test.js' {
  declare module.exports: $Exports<'styled-components/src/test/expanded-api.test'>;
}
declare module 'styled-components/src/test/extending.test.js' {
  declare module.exports: $Exports<'styled-components/src/test/extending.test'>;
}
declare module 'styled-components/src/test/globals.js' {
  declare module.exports: $Exports<'styled-components/src/test/globals'>;
}
declare module 'styled-components/src/test/overriding.test.js' {
  declare module.exports: $Exports<'styled-components/src/test/overriding.test'>;
}
declare module 'styled-components/src/test/props.test.js' {
  declare module.exports: $Exports<'styled-components/src/test/props.test'>;
}
declare module 'styled-components/src/test/rehydration.test.js' {
  declare module.exports: $Exports<'styled-components/src/test/rehydration.test'>;
}
declare module 'styled-components/src/test/ssr.test.js' {
  declare module.exports: $Exports<'styled-components/src/test/ssr.test'>;
}
declare module 'styled-components/src/test/staticCaching.test.js' {
  declare module.exports: $Exports<'styled-components/src/test/staticCaching.test'>;
}
declare module 'styled-components/src/test/styles.test.js' {
  declare module.exports: $Exports<'styled-components/src/test/styles.test'>;
}
declare module 'styled-components/src/test/theme.test.js' {
  declare module.exports: $Exports<'styled-components/src/test/theme.test'>;
}
declare module 'styled-components/src/test/utils.js' {
  declare module.exports: $Exports<'styled-components/src/test/utils'>;
}
declare module 'styled-components/src/test/warnTooManyClasses.test.js' {
  declare module.exports: $Exports<'styled-components/src/test/warnTooManyClasses.test'>;
}
declare module 'styled-components/src/types.js' {
  declare module.exports: $Exports<'styled-components/src/types'>;
}
declare module 'styled-components/src/utils/consolidateStreamedStyles.js' {
  declare module.exports: $Exports<'styled-components/src/utils/consolidateStreamedStyles'>;
}
declare module 'styled-components/src/utils/create-broadcast.js' {
  declare module.exports: $Exports<'styled-components/src/utils/create-broadcast'>;
}
declare module 'styled-components/src/utils/createWarnTooManyClasses.js' {
  declare module.exports: $Exports<'styled-components/src/utils/createWarnTooManyClasses'>;
}
declare module 'styled-components/src/utils/determineTheme.js' {
  declare module.exports: $Exports<'styled-components/src/utils/determineTheme'>;
}
declare module 'styled-components/src/utils/domElements.js' {
  declare module.exports: $Exports<'styled-components/src/utils/domElements'>;
}
declare module 'styled-components/src/utils/empties.js' {
  declare module.exports: $Exports<'styled-components/src/utils/empties'>;
}
declare module 'styled-components/src/utils/error.js' {
  declare module.exports: $Exports<'styled-components/src/utils/error'>;
}
declare module 'styled-components/src/utils/escape.js' {
  declare module.exports: $Exports<'styled-components/src/utils/escape'>;
}
declare module 'styled-components/src/utils/extractCompsFromCSS.js' {
  declare module.exports: $Exports<'styled-components/src/utils/extractCompsFromCSS'>;
}
declare module 'styled-components/src/utils/flatten.js' {
  declare module.exports: $Exports<'styled-components/src/utils/flatten'>;
}
declare module 'styled-components/src/utils/generateAlphabeticName.js' {
  declare module.exports: $Exports<'styled-components/src/utils/generateAlphabeticName'>;
}
declare module 'styled-components/src/utils/generateDisplayName.js' {
  declare module.exports: $Exports<'styled-components/src/utils/generateDisplayName'>;
}
declare module 'styled-components/src/utils/getComponentName.js' {
  declare module.exports: $Exports<'styled-components/src/utils/getComponentName'>;
}
declare module 'styled-components/src/utils/hasInInheritanceChain.js' {
  declare module.exports: $Exports<'styled-components/src/utils/hasInInheritanceChain'>;
}
declare module 'styled-components/src/utils/insertRuleHelpers.js' {
  declare module.exports: $Exports<'styled-components/src/utils/insertRuleHelpers'>;
}
declare module 'styled-components/src/utils/interleave.js' {
  declare module.exports: $Exports<'styled-components/src/utils/interleave'>;
}
declare module 'styled-components/src/utils/isPlainObject.js' {
  declare module.exports: $Exports<'styled-components/src/utils/isPlainObject'>;
}
declare module 'styled-components/src/utils/isStyledComponent.js' {
  declare module.exports: $Exports<'styled-components/src/utils/isStyledComponent'>;
}
declare module 'styled-components/src/utils/isTag.js' {
  declare module.exports: $Exports<'styled-components/src/utils/isTag'>;
}
declare module 'styled-components/src/utils/nonce.js' {
  declare module.exports: $Exports<'styled-components/src/utils/nonce'>;
}
declare module 'styled-components/src/utils/once.js' {
  declare module.exports: $Exports<'styled-components/src/utils/once'>;
}
declare module 'styled-components/src/utils/stringifyRules.js' {
  declare module.exports: $Exports<'styled-components/src/utils/stringifyRules'>;
}
declare module 'styled-components/src/utils/styleNames.js' {
  declare module.exports: $Exports<'styled-components/src/utils/styleNames'>;
}
declare module 'styled-components/src/utils/test/determineTheme.test.js' {
  declare module.exports: $Exports<'styled-components/src/utils/test/determineTheme.test'>;
}
declare module 'styled-components/src/utils/test/error.test.js' {
  declare module.exports: $Exports<'styled-components/src/utils/test/error.test'>;
}
declare module 'styled-components/src/utils/test/escape.test.js' {
  declare module.exports: $Exports<'styled-components/src/utils/test/escape.test'>;
}
declare module 'styled-components/src/utils/test/extractCompsFromCSS.test.js' {
  declare module.exports: $Exports<'styled-components/src/utils/test/extractCompsFromCSS.test'>;
}
declare module 'styled-components/src/utils/test/flatten.test.js' {
  declare module.exports: $Exports<'styled-components/src/utils/test/flatten.test'>;
}
declare module 'styled-components/src/utils/test/generateAlphabeticName.test.js' {
  declare module.exports: $Exports<'styled-components/src/utils/test/generateAlphabeticName.test'>;
}
declare module 'styled-components/src/utils/test/generateDisplayName.test.js' {
  declare module.exports: $Exports<'styled-components/src/utils/test/generateDisplayName.test'>;
}
declare module 'styled-components/src/utils/test/getComponentName.test.js' {
  declare module.exports: $Exports<'styled-components/src/utils/test/getComponentName.test'>;
}
declare module 'styled-components/src/utils/test/interleave.test.js' {
  declare module.exports: $Exports<'styled-components/src/utils/test/interleave.test'>;
}
declare module 'styled-components/src/utils/test/styleNames.test.js' {
  declare module.exports: $Exports<'styled-components/src/utils/test/styleNames.test'>;
}
declare module 'styled-components/src/utils/test/validAttr.test.js' {
  declare module.exports: $Exports<'styled-components/src/utils/test/validAttr.test'>;
}
declare module 'styled-components/src/utils/validAttr.js' {
  declare module.exports: $Exports<'styled-components/src/utils/validAttr'>;
}
declare module 'styled-components/src/vendor/glamor/hash.js' {
  declare module.exports: $Exports<'styled-components/src/vendor/glamor/hash'>;
}
declare module 'styled-components/src/vendor/postcss-nested/index.js' {
  declare module.exports: $Exports<'styled-components/src/vendor/postcss-nested/index'>;
}
declare module 'styled-components/src/vendor/postcss-safe-parser/parse.js' {
  declare module.exports: $Exports<'styled-components/src/vendor/postcss-safe-parser/parse'>;
}
declare module 'styled-components/src/vendor/postcss-safe-parser/safe-parser.js' {
  declare module.exports: $Exports<'styled-components/src/vendor/postcss-safe-parser/safe-parser'>;
}
declare module 'styled-components/src/vendor/postcss/at-rule.js' {
  declare module.exports: $Exports<'styled-components/src/vendor/postcss/at-rule'>;
}
declare module 'styled-components/src/vendor/postcss/comment.js' {
  declare module.exports: $Exports<'styled-components/src/vendor/postcss/comment'>;
}
declare module 'styled-components/src/vendor/postcss/container.js' {
  declare module.exports: $Exports<'styled-components/src/vendor/postcss/container'>;
}
declare module 'styled-components/src/vendor/postcss/css-syntax-error.js' {
  declare module.exports: $Exports<'styled-components/src/vendor/postcss/css-syntax-error'>;
}
declare module 'styled-components/src/vendor/postcss/declaration.js' {
  declare module.exports: $Exports<'styled-components/src/vendor/postcss/declaration'>;
}
declare module 'styled-components/src/vendor/postcss/input.js' {
  declare module.exports: $Exports<'styled-components/src/vendor/postcss/input'>;
}
declare module 'styled-components/src/vendor/postcss/lazy-result.js' {
  declare module.exports: $Exports<'styled-components/src/vendor/postcss/lazy-result'>;
}
declare module 'styled-components/src/vendor/postcss/list.js' {
  declare module.exports: $Exports<'styled-components/src/vendor/postcss/list'>;
}
declare module 'styled-components/src/vendor/postcss/node.js' {
  declare module.exports: $Exports<'styled-components/src/vendor/postcss/node'>;
}
declare module 'styled-components/src/vendor/postcss/parse.js' {
  declare module.exports: $Exports<'styled-components/src/vendor/postcss/parse'>;
}
declare module 'styled-components/src/vendor/postcss/parser.js' {
  declare module.exports: $Exports<'styled-components/src/vendor/postcss/parser'>;
}
declare module 'styled-components/src/vendor/postcss/postcss.js' {
  declare module.exports: $Exports<'styled-components/src/vendor/postcss/postcss'>;
}
declare module 'styled-components/src/vendor/postcss/processor.js' {
  declare module.exports: $Exports<'styled-components/src/vendor/postcss/processor'>;
}
declare module 'styled-components/src/vendor/postcss/result.js' {
  declare module.exports: $Exports<'styled-components/src/vendor/postcss/result'>;
}
declare module 'styled-components/src/vendor/postcss/root.js' {
  declare module.exports: $Exports<'styled-components/src/vendor/postcss/root'>;
}
declare module 'styled-components/src/vendor/postcss/rule.js' {
  declare module.exports: $Exports<'styled-components/src/vendor/postcss/rule'>;
}
declare module 'styled-components/src/vendor/postcss/stringifier.js' {
  declare module.exports: $Exports<'styled-components/src/vendor/postcss/stringifier'>;
}
declare module 'styled-components/src/vendor/postcss/stringify.js' {
  declare module.exports: $Exports<'styled-components/src/vendor/postcss/stringify'>;
}
declare module 'styled-components/src/vendor/postcss/terminal-highlight.js' {
  declare module.exports: $Exports<'styled-components/src/vendor/postcss/terminal-highlight'>;
}
declare module 'styled-components/src/vendor/postcss/tokenize.js' {
  declare module.exports: $Exports<'styled-components/src/vendor/postcss/tokenize'>;
}
declare module 'styled-components/src/vendor/postcss/vendor.js' {
  declare module.exports: $Exports<'styled-components/src/vendor/postcss/vendor'>;
}
declare module 'styled-components/src/vendor/postcss/warn-once.js' {
  declare module.exports: $Exports<'styled-components/src/vendor/postcss/warn-once'>;
}
declare module 'styled-components/src/vendor/postcss/warning.js' {
  declare module.exports: $Exports<'styled-components/src/vendor/postcss/warning'>;
}
declare module 'styled-components/test-utils/index.js' {
  declare module.exports: $Exports<'styled-components/test-utils/index'>;
}
declare module 'styled-components/test-utils/setupTestFramework.js' {
  declare module.exports: $Exports<'styled-components/test-utils/setupTestFramework'>;
}
